project:
  type: website
  output-dir: docs

freeze: true

# Enable banner style title blocks
title-block-banner: false

website:
  open-graph: true
  sidebar: 
    style: "docked"
  navbar:
    pinned: false
    left:
      - text: About Me
        href: index.qmd
      - icon: github
        href: https://github.com/YYZhang2025
      - icon: linkedin
        href: https://www.linkedin.com/in/zhang-yuyang/

    right:
      - text: Blogs
        href: ./posts/blogs.qmd
      - text: Projects
        href: ./posts/projects.qmd
      - text: Learning Notes
        href: ./posts/notes.qmd
      
      - text: 100 Papers with Code
        href: https://yuyang.info/100-AI-Papers/

  favicon: "./style/icon.avif"
format:
  html:
    theme:
      light: [simplex, ./style/light.scss]
      dark: [darkly, ./style/dark.scss]
    css: ./style/styles.css

    toc-title: On this page
    toc: true
    toc-location: left
    toc-expand: 2

    # code-fold: true
    code-summary: "Show the code"
    code-block-background: true
    code-copy: true
    code-overflow: scroll
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: github
    code-line-numbers: false

    link-external-icon: false
    link-external-newwindow: true
    execute:
      enabled: false
      freeze: true

    citations-hover: true

    linestretch: 1.3

    fontsize: 1.3em
    header-includes: <link href="https://fonts.cdnfonts.com/css/cmu-sans-serif" rel="stylesheet">
    mainfont: MyFont

    indent: true
    grid:
      body-width: 1200px

    number-sections: true
