project:
  type: website
  output-dir: docs

freeze: true

# Enable banner style title blocks
title-block-banner: false

website:
  open-graph: true
  navbar:
    pinned: false
    left:
      - text: About Me
        href: ./posts/about.qmd

    right:
      - text: Blogs
        href: index.qmd
      - text: Projects
        href: ./posts/projects.qmd
      - text: Learning Notes
        href: ./posts/notes.qmd
      - icon: github
        href: https://github.com/Yyzhang2000
      - icon: linkedin
        href: https://www.linkedin.com/in/zhang-yuyang/

  favicon: "./style/icon.avif"
format:
  html:
    image-height: 300x
    image-width: 400px
    theme:
      light: [simplex, ./style/light.scss]
      dark: [darkly, ./style/dark.scss]
    css: ./style/styles.css

    toc-title: Contents
    toc: true
    toc-location: left
    toc-expand: 1

    code-overflow: scroll
    # code-fold: true
    code-block-bg: true
    code-summary: "Show the code"
    code-line-numbers: false
    code-block-background: true

    highlight-style: github

    link-external-icon: false
    link-external-newwindow: true
    execute:
      enabled: false
      freeze: true

    citations-hover: true

    linestretch: 1.3

    fontsize: 1.2em
    header-includes: <link href="https://fonts.cdnfonts.com/css/cmu-sans-serif" rel="stylesheet">
    mainfont: MyFont

    indent: true
    grid:
      body-width: 1000px
