project:
  type: website
  output-dir: docs

freeze: true

title-block-banner: false

website:
  site-url: "https://yuyang.info/"
  bread-crumbs: false
  back-to-top-navigation: true
  open-graph: true
  sidebar: 
    style: "docked"
  navbar:
    pinned: false
    left:
      - text: About Me
        href: index.qmd
      - icon: github
        href: https://github.com/YYZhang2025
      - icon: linkedin
        href: https://www.linkedin.com/in/zhang-yuyang/

    right:
      - text: Blogs
        href: ./posts/blogs.qmd
      - text: Projects
        href: ./posts/projects.qmd
      - text: 100 Papers with Code
        href: https://yuyang.info/100-AI-Papers/

  favicon: "./style/icon.avif"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Yuyang, 2025"
    background: "#D9E3E4"
format:
  html:
    theme:
      light: [simplex, ./style/light.scss]
      dark: [darkly, ./style/dark.scss]
    css: ./style/styles.css

    toc-title: On this page
    toc: true
    toc-location: left-body
    toc-expand: 1

    # code-fold: true
    code-summary: "Show the code"
    code-block-background: true
    code-copy: true
    code-overflow: scroll
    code-block-bg: true
    code-block-border-left: "#31bbe96b"
    highlight-style: github
    code-line-numbers: true

    link-external-icon: false
    link-external-newwindow: true
    

    citations-hover: true

    linestretch: 1.4


    indent: true
    grid:
      body-width: 1000px
      gutter-width: 3rem

    number-sections: true

    
    
    header-includes: [
      <link href="https://fonts.cdnfonts.com/css/cmu-sans-serif" rel="stylesheet">,
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    ]



execute:
  echo: false
  enabled: false



filters: 
  - line-highlight
 